Controllers/CarrinhoCompraController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using LanchoneteMVC.Models;
using LanchoneteMVC.Repositories.Interfaces;
using LanchoneteMVC.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace LanchoneteMVC.Controllers
{
    public class CarrinhoCompraController : Controller
    {
        private readonly ILancheRepository _lancheRepository;
        private readonly ICarrinhoCompraRepository _carrinhoCompraRepository;

        public CarrinhoCompraController(ILancheRepository lancheRepository, ICarrinhoCompraRepository carrinhoCompraRepository)
        {
            _lancheRepository = lancheRepository;
            _carrinhoCompraRepository = carrinhoCompraRepository;
        }

        public IActionResult Index()
        {
            var itens = _carrinhoCompraRepository.GetCarrinhoCompraItems();

            _carrinhoCompraRepository.GetCarrinhoCompra().carrinhoCompraItems = itens;

            var carrinhoCompraVM = new CarrinhoCompraViewModel
            {
                CarrinhoCompra = _carrinhoCompraRepository.GetCarrinhoCompra(),
                CarrinhoCompraTotal = _carrinhoCompraRepository.GetCarrinhoCompraTotal()
            };

            return View(carrinhoCompraVM);
        }
        public IActionResult AdicionarItemNoCarrinhoCompra(int Id)
        {
            var lancheSelecionado = _lancheRepository.Lanches.FirstOrDefault((lanche) => lanche.Id == Id);

            if (lancheSelecionado != null)
            {
                _carrinhoCompraRepository.AdicionarAoCarrinho(lancheSelecionado);
            }

            return RedirectToAction("Index");
        }
        public IActionResult RemoverItemNoCarrinhoCompra(int Id)
        {
            var lancheSelecionado = _lancheRepository.Lanches.FirstOrDefault((lanche) => lanche.Id == Id);

            if (lancheSelecionado != null)
            {
                _carrinhoCompraRepository.RemoverDoCarrinho(lancheSelecionado);
            }
            return RedirectToAction("Index");
        }
    }
}

Controllers/ContatoController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace LanchoneteMVC.Controllers
{
    public class ContatoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/LancheController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using LanchoneteMVC.Models;
using LanchoneteMVC.Repositories.Interfaces;
using LanchoneteMVC.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.IdentityModel.Tokens;

namespace LanchoneteMVC.Controllers
{
    public class LancheController : Controller
    {
        private readonly ILancheRepository _lancheRepository;

        public LancheController(ILancheRepository lancheRepository)
        {
            _lancheRepository = lancheRepository;
        }

        public IActionResult List(string categoria)
        {
            IEnumerable<Lanche> lanches;
            string CategoriaAtual = "";

            if (string.IsNullOrEmpty(categoria))
            {
                lanches = _lancheRepository.Lanches.OrderBy(lanche => lanche.Id);
            }
            else
            {
                lanches = _lancheRepository.Lanches.Where(lanche => lanche.Categoria.CategoriaNome.Equals(categoria));
            }
            return View(LancheListViewModel.GetLancheListViewModel(lanches, CategoriaAtual));
        }

        public IActionResult Details(int Id)
        {
            var lanche = _lancheRepository.Lanches.FirstOrDefault(lanche => lanche.Id == Id);
            return View(lanche);
        }
        public IActionResult Search(string searchString)
        {
            IEnumerable<Lanche> lanches;
            string CategoriaAtual = string.Empty;
            if (string.IsNullOrEmpty(searchString))
            {
                lanches = _lancheRepository.Lanches.OrderBy(lanche => lanche.Id);
                CategoriaAtual = "Todos os Lanches";
            }
            else
            {
                lanches = _lancheRepository.Lanches.Where(lanche => lanche.Nome.ToLower().Contains(searchString.ToLower()));
                if (lanches.Any())
                    CategoriaAtual = "Lanches";
                else
                    CategoriaAtual = "Nenhum lanche foi encontrado";
            }

            return View("~/Views/Lanche/List.cshtml", new LancheListViewModel
            {
                Lanches = lanches,
                CategoriaAtual = CategoriaAtual
            });
        }

        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Views/Shared/_Carousel.cshtml
<div id="carouselLanches" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="~/images/carousel11.jpg" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="~/images/carousel12.jpg" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="~/images/carousel13.jpg" class="d-block w-100" alt="...">
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselLanches" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselLanches" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

Views/Shared/_LanchesResume.cshtml
@using System.Globalization
@model Lanche

<div class="col-sm-4 col-md-4 col-lg-4">
    <p>@Model.ImagemUrl</p>
    <h3>Preço: @Model.Preco.ToString("c", CultureInfo.CreateSpecificCulture("pt-BR"))</h3>
    <h4>
        <a asp-controller="Lanche" asp-action="Details" asp-route-Id="@Model.Id">@Model.Nome</a>
    </h4>
    <p>Descrição Curta: @Model.DescricaoCurta</p>
    <div>
        <p class="button">
            <a class="btn btn-primary" id="cartButton" asp-controller="CarrinhoCompra"
                asp-action="AdicionarItemNoCarrinhoCompra" asp-route-Id="@Model.Id">
                Incluir no Carrinho
            </a>
        </p>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lanchonete</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Lanchonete.styles.css" asp-append-version="true" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    Lanchonete
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Contato"
                                asp-action="Index">Contato</a>
                        </li>
                        <li class="nav-item">
                            @await Component.InvokeAsync("CategoriaMenu")
                        </li>
                        <li class="nav-item">
                            <form class="navbar-form navbar-right" asp-controller="Lanche" asp-action="Search"
                                method="get">
                                <div class="form-group">
                                    <input type="text" class="form-control" name="searchString"
                                        placeholder="Procurar produto" value="@ViewData["searchString"]">
                                </div>
                            </form>
                        </li>
                        <li class="nav-item">
                            @await Component.InvokeAsync("CarrinhoCompraResumo")
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Lanchonete - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>