Models/CarrinhoCompra.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace LanchoneteMVC.Models
{
    [Table("CarrinhoCompra")]
    public class CarrinhoCompra
    {
        [StringLength(200)]
        public string Id { get; set; }
        public List<CarrinhoCompraItem> carrinhoCompraItems { get; set; }
    }
}

ViewModels/CarrinhoCompraViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LanchoneteMVC.Models;

namespace LanchoneteMVC.ViewModels
{
    public class CarrinhoCompraViewModel
    {
        public CarrinhoCompra CarrinhoCompra { get; set; }
        public decimal CarrinhoCompraTotal { get; set; }
    }
}

Controllers/CarrinhoCompraController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using LanchoneteMVC.Models;
using LanchoneteMVC.Repositories.Interfaces;
using LanchoneteMVC.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace LanchoneteMVC.Controllers
{
    public class CarrinhoCompraController : Controller
    {
        private readonly ILancheRepository _lancheRepository;
        private readonly ICarrinhoCompraRepository _carrinhoCompraRepository;

        public CarrinhoCompraController(ILancheRepository lancheRepository, ICarrinhoCompraRepository carrinhoCompraRepository)
        {
            _lancheRepository = lancheRepository;
            _carrinhoCompraRepository = carrinhoCompraRepository;
        }

        public IActionResult Index()
        {
            var itens = _carrinhoCompraRepository.GetCarrinhoCompraItems();

            _carrinhoCompraRepository.GetCarrinhoCompra().carrinhoCompraItems = itens;

            var carrinhoCompraVM = new CarrinhoCompraViewModel
            {
                CarrinhoCompra = _carrinhoCompraRepository.GetCarrinhoCompra(),
                CarrinhoCompraTotal = _carrinhoCompraRepository.GetCarrinhoCompraTotal()
            };

            return View(carrinhoCompraVM);
        }
        public IActionResult AdicionarItemNoCarrinhoCompra(int Id)
        {
            var lancheSelecionado = _lancheRepository.Lanches.FirstOrDefault((lanche) => lanche.Id == Id);

            if (lancheSelecionado != null)
            {
                _carrinhoCompraRepository.AdicionarAoCarrinho(lancheSelecionado);
            }

            return RedirectToAction("Index");
        }
        public IActionResult RemoverItemNoCarrinhoCompra(int Id)
        {
            var lancheSelecionado = _lancheRepository.Lanches.FirstOrDefault((lanche) => lanche.Id == Id);

            if (lancheSelecionado != null)
            {
                _carrinhoCompraRepository.RemoverDoCarrinho(lancheSelecionado);
            }
            return RedirectToAction("Index");
        }
    }
}

Controllers/LancheController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using LanchoneteMVC.Models;
using LanchoneteMVC.Repositories.Interfaces;
using LanchoneteMVC.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.IdentityModel.Tokens;

namespace LanchoneteMVC.Controllers
{
    public class LancheController : Controller
    {
        private readonly ILancheRepository _lancheRepository;

        public LancheController(ILancheRepository lancheRepository)
        {
            _lancheRepository = lancheRepository;
        }

        public IActionResult List(string categoria)
        {
            IEnumerable<Lanche> lanches;
            string CategoriaAtual = "";

            if (string.IsNullOrEmpty(categoria))
            {
                lanches = _lancheRepository.Lanches.OrderBy(lanche => lanche.Id);
            }
            else
            {
                lanches = _lancheRepository.Lanches.Where(lanche => lanche.Categoria.CategoriaNome.Equals(categoria));
            }
            return View(LancheListViewModel.GetLancheListViewModel(lanches, CategoriaAtual));
        }

        public IActionResult Details(int Id)
        {
            var lanche = _lancheRepository.Lanches.FirstOrDefault(lanche => lanche.Id == Id);
            return View(lanche);
        }
        public IActionResult Search(string searchString)
        {
            IEnumerable<Lanche> lanches;
            string CategoriaAtual = string.Empty;
            if (string.IsNullOrEmpty(searchString))
            {
                lanches = _lancheRepository.Lanches.OrderBy(lanche => lanche.Id);
                CategoriaAtual = "Todos os Lanches";
            }
            else
            {
                lanches = _lancheRepository.Lanches.Where(lanche => lanche.Nome.ToLower().Contains(searchString.ToLower()));
                if (lanches.Any())
                    CategoriaAtual = "Lanches";
                else
                    CategoriaAtual = "Nenhum lanche foi encontrado";
            }

            return View("~/Views/Lanche/List.cshtml", new LancheListViewModel
            {
                Lanches = lanches,
                CategoriaAtual = CategoriaAtual
            });
        }

        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Controllers/PedidoController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using LanchoneteMVC.Models;
using LanchoneteMVC.Repositories.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace LanchoneteMVC.Controllers
{
    public class PedidoController : Controller
    {
        private readonly IPedidoRepository _pedidoRepository;
        private readonly ICarrinhoCompraRepository _carrinhoCompra;

        public PedidoController(IPedidoRepository pedidoRepository, ICarrinhoCompraRepository carrinhoCompra)
        {
            _pedidoRepository = pedidoRepository;
            _carrinhoCompra = carrinhoCompra;
        }
        [HttpGet]
        public IActionResult Checkout()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Checkout(Pedido pedido)
        {
            int totalItensPedido = 0;
            decimal precoTotalPedido = 0.0m;

            //obtem os itens do carrinho de compra do cliente
            List<CarrinhoCompraItem> items = _carrinhoCompra.GetCarrinhoCompraItems();
            if (items.Count() == 0)
            {
                ModelState.AddModelError("", "Seu carrinho está vazio, que tal incluir um lanche?");
            }

            //Calcular o total de itens e o total do pedido
            foreach (var item in items)
            {
                totalItensPedido += item.Quantidade;
                precoTotalPedido += item.Lanche.Preco * item.Quantidade;
            }
            //atribui os valores obtidos ao pedido
            pedido.TotalItensPedido = totalItensPedido;
            pedido.PedidoTotal = precoTotalPedido;

            //validar os dados do pedido
            if (ModelState.IsValid)
            {
                //cria o pedido e os detalhes
                _pedidoRepository.CriarPedido(pedido);

                //define mensagens ao cliente
                ViewBag.CheckoutCompletoMensagem = "Obrigado pelo seu pedido :)";
                ViewBag.TotalPedido = _carrinhoCompra.GetCarrinhoCompraTotal();

                //limpar carrinho
                _carrinhoCompra.LimparCarrinho();

                //exibe a view com dados do cliente e do pedido
                return View("~/Views/Pedido/CheckoutCompleto.cshtml", pedido);
            }
            return View(pedido);
        }
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Views/CarrinhoCompra/Index.cshtml
@using System.Globalization
@model CarrinhoCompraViewModel

<dir class="container">
    <div class="row">
        <span>img</span>
        <div>
            <h4> Seu Carrinho de compras:</h4>
        </div>
    </div>
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Quantidade</th>
                <th>Lanche</th>
                <th class="text-right">Preço</th>
                <th class="text-right">Subtotal</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.CarrinhoCompra.carrinhoCompraItems)
            {
                <tr>
                    <td class="text-center">@item.Quantidade</td>
                    <td class="text-left">@item.Lanche.Nome</td>
                    <td class="text-right">@item.Lanche.Preco.ToString("c", CultureInfo.CreateSpecificCulture("pt-BR"))</td>
                    <td class="text-right">
                        @((item.Quantidade * item.Lanche.Preco).ToString("c", CultureInfo.CreateSpecificCulture("pt-BR")))
                    </td>
                    <td class="text-center">
                        <a asp-controller="CarrinhoCompra" asp-action="RemoverItemNoCarrinhoCompra"
                            asp-route-Id="@item.Lanche.Id"><span>Remover</span>
                        </a>
                    </td>
                </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <td colspan="3" class="text-right">Total:</td>
                <td class="tex-right">
                    @Model.CarrinhoCompraTotal.ToString("c", CultureInfo.CreateSpecificCulture("pt-BR"))
                </td>
            </tr>
        </tfoot>
    </table>
    <div class="text-right">
        <div class="btn-group">
            <a class="btn btn-success" asp-controller="Pedido" asp-action="Checkout">Encerrar Pedido</a>
            <a class="btn btn-primary" asp-controller="Lanche" asp-action="List">Continuar Comprando</a>
        </div>
    </div>
</dir>